### ISSUE TITLE
Not Working with Python

### ISSUE THREAD

**Issue by chookity-pokk** [zbelial/treesitter-context.el#14]
I have this installed as well as posframe-plus and I have it setup to be used with Python but no matter what I do it doesn't show up in a Python buffer correctly. I essentially just get an empty grey box in the top corner. I've tried toggling on/off `python-ts-mode` and it doesn't seem to change the box at all. I am also not seeing any errors in the Messages buffer.

![image](https://github.com/zbelial/treesitter-context.el/assets/24358100/6f18af7f-529c-4019-81f4-1713ceac5785)

Below is my OS, Emacs and config info. 

OS:
MacOS 13.5.1 (Macbook Pro M2)

Emacs:
29.1

Config:
`(add-hook 'python-ts-mode-hook #'treesitter-context-mode)`

**Comment by zbelial** [comment]
Hi, thanks for giving this package a try. 
It seems that treesitter-context did not succeed in query and capture nodes. Could you test again according to the following steps in a python buffer with python-ts-mode enabled? Thanks.
1. What does `M-: (treesit-query-validate 'python treesitter-context--python-query)` say?
Normally it should print "QUERY is valid" in `*Message*`.

2. If "QUERY is valid", what does `M-: (treesitter-context-collect-contexts)` return if you put the cursor in a for statement?
It should print something like "((10 #("for _ in range(1000):
" 0 3 (face font-lock-keyword-face fontified t) 3 6 (fontified t) 6 8 (face font-lock-keyword-face fontified t) 8 9 (fontified t) 9 14 (face font-lock-builtin-face fontified t) 14 15 (fontified t) 15 19 (face font-lock-number-face fontified t) 19 21 (fontified t))))"

3. If none of the above tests work as expected, you can redefine `treesitter-context--refresh-context` to 
```elisp
;; do not forget to make this new definition effective with `eval-last-sexp'.
(defun treesitter-context--refresh-context ()
  "Refresh context at the point."
  (unless (or (minibufferp)
              (equal (buffer-name) treesitter-context--buffer-name))
    (setq treesitter-context--context-list nil)
    (setq treesitter-context--context-list (treesitter-context-collect-contexts))
    (treesitter-context--show-context)))
```
and toggle debug with `toggle-debug-on-error` to see if there is any error. 

4. If there is no error, I don't know what to do then. But let's see what the above three tests say first. :)

**Comment by chookity-pokk** [comment]
Thanks for the reply!

In the first step I get that the QUERY is valid but for the for loop test I get `nil` no matter where I put my cursor (I put it in statements, loops, variable declarations and imports). 

Unfortunately I don't get any errors either. Though I am able to use the [combobulate](https://github.com/mickeynp/combobulate) package to do queries successfully.

**Comment by zbelial** [comment]
Another person on emacs reddit also said treesitter-context didn't work for him, and he used macOS too, but I don't have any macos computers, so I cannot test and figure out the problem. 

Maybe I should read combobulate's code and hope I could find some useful things from it.

**Comment by chookity-pokk** [comment]
Can you point me to their thread? Maybe the two of us can talk and see what we find. I honestly just started using MacOS because it's a work laptop so I know almost nothing about it.

**Comment by zbelial** [comment]
Hi @chookity-pokk 
I rechecked the reddit thread and found the user reporting issues used Debian 12, not macOS. Sorry for misremembering that. 

And sorry again that I cannot help you ATM as it works for me. If you have some free time, can you post a minimum recipe to reproduce the problem? I wish that would not waste you too much time.

**Comment by zbelial** [comment]
What's the value of `treesitter-context-show-context-always`?   The default value is nil, which means only when the root node of  the current node is invisible, the context will be showed. If yours is nil, change it to t and see if it works.

**Comment by zbelial** [comment]
I should improve the README to help users understand how to use this package.

**Comment by chookity-pokk** [comment]
Here is basically what I did to setup treesitter for MacOS. 

I started by installing treesitter with Homebrew using the command `brew install tree-sitter`. I then followed the steps from [here](https://git.savannah.gnu.org/cgit/emacs.git/tree/admin/notes/tree-sitter/starter-guide?h=feature/tree-sitter), including installing the grammars. After that I went and installed this package using the built in `use-package` (I'll put that code below). Then I put in my init code for tree-sitter and this package (below as well). After that I went and tried opening a Python file and got the results listed above.

Tree-sitter init:
```
(require 'treesit)

(add-hook 'python-mode-hook 'python-ts-mode)
(global-set-key (kbd "C-c e") 'treesit-explore-mode)
```

Tree-sitter Context init:
```
(use-package treesitter-context
  :init (slot/vc-install :fetcher "github" :repo "zbelial/posframe-plus"))

(use-package treesitter-context
  :init (slot/vc-install :fetcher "github" :repo "zbelial/treesitter-context.el"))

(add-hook 'python-ts-mode-hook #'treesitter-context-mode)

;; Included later
(defun treesitter-context--refresh-context ()
  "Refresh context at the point."
  (unless (or (minibufferp)
              (equal (buffer-name) treesitter-context--buffer-name))
    (setq treesitter-context--context-list nil)
    (setq treesitter-context--context-list (treesitter-context-collect-contexts))
    (treesitter-context--show-context)))
```

My `use-packge` init code:
```
(cl-defun slot/vc-install (&key (fetcher "github") repo name rev backend)
  "Install a package from a remote if it's not already installed.
This is a thin wrapper around `package-vc-install' in order to
make non-interactive usage more ergonomic.  Takes the following
named arguments:

- FETCHER the remote where to get the package (e.g., \"gitlab\").
  If omitted, this defaults to \"github\".

- REPO should be the name of the repository (e.g.,
  \"slotThe/arXiv-citation\".

- NAME, REV, and BACKEND are as in `package-vc-install' (which
  see)."
  (let* ((url (format "https://www.%s.com/%s" fetcher repo))
         (iname (when name (intern name)))
         (pac-name (or iname (intern (file-name-base repo)))))
    (unless (package-installed-p pac-name)
      (package-vc-install url iname rev backend))))
```

Also, no worries! This package seems super cool and I'm sure at some point I can get it working.

`treesitter-context-show-context-always` gave me a value of `nil`, unfortunately.

**Comment by zbelial** [comment]
Thanks!
> treesitter-context-show-context-always gave me a value of nil, unfortunately.

I guess this is the root cause. You can change its value via `(setq treesitter-context-show-context-always t)` and see whether it works or not.

**Comment by zbelial** [comment]
In your screenshot, I think the root node is a class definition(the class **Testing**), and it's visible in the window.  If `treesitter-context-show-context-always` is nil and the root node is visible, no context will be shown in the child frame. 

I forgot `treesitter-context-show-context-always`'s existence, let alone its default value is nil. 

I've changed its default value and pushed this change to github a moment ago.

**Comment by chookity-pokk** [comment]
Okay, so to clarify here, would the context only show up if it's off screen?

I'll do an update and let you know what happens!

**Comment by zbelial** [comment]
> Okay, so to clarify here, would the context only show up if it's off screen?
> 
> I'll do an update and let you know what happens!

If `treesitter-context-show-context-always` is `t`, the context will always show up; otherwise, when it's `nil` the context only show up when current node's root node is off screen.

**Comment by chookity-pokk** [comment]
Oooh, okay. I get it now. Good news, it seems to be working! Don't mind the ridiculous code, I was just looking to fill up space within nonsense. Thank you so much for the help and the great package!

![image](https://github.com/zbelial/treesitter-context.el/assets/24358100/313a6c41-18c3-4b5f-b701-2c9eaa9a3867)

**Comment by zbelial** [comment]
Yes!
Thanks you very much for helping me to be aware of `treesitter-context-show-context-always` (I set it to `t` in my init.el and then forgot about it totally), and your issue reminded me to improve the README.
