### ISSUE TITLE
List all customizable options and explain them

### ISSUE THREAD

**Issue by zbelial** [zbelial/treesitter-context.el#15]

**Comment by chookity-pokk** [comment]
My elisp is pretty weak (read as nonexistent) but I can likely take care of this if you point me in the right direction. Would it just be the `defcustom`'s in the `treesitter-context.el`?

**Comment by zbelial** [comment]
Thanks. 

Yes,  but there is also a `defcustom` in `treesitter-context-java.el`, and this one is only used for java. 

Welcome any contribution very much.

**Comment by zbelial** [comment]
Thanks @chookity-pokk, closing this issue. 

Fixed in 66b6cf42a27e241cb2519619d8980119ec24348a.
